### ISSUE TITLE
Intermittent SharePoint Online exception when creating site collections

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#126]
In Step 14: Create Site Collections, a number of site collections are created successfully, then SharePoint online throws an exception:

Successfully added users to group: [MyClientName] Visitors
Exception occurred while creating site collection: An error occurred during the web service call.
Creating Matter Center Interfaces group.
Exception occurred while creating group: The remote server returned an error: (401) Unauthorized.
Exception occurred while assigning permissions: The remote server returned an error: (401) Unauthorized.
Exception occurred while assigning permissions: The remote server returned an error: (401) Unauthorized.
Message: The remote server returned an error: (401) Unauthorized.
Stacktrace:    at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateSiteCollection.Program.ActivateFeature(String clientUrl, SharePointOnlineCredentials credentials)
Exception occurred while creating site collection: An error occurred during the web service call.
Creating Matter Center Interfaces group.
Exception occurred while creating group: The remote server returned an error: (401) Unauthorized.
Exception occurred while assigning permissions: The remote server returned an error: (401) Unauthorized.
Exception occurred while assigning permissions: The remote server returned an error: (401) Unauthorized.
Message: The remote server returned an error: (401) Unauthorized.
Stacktrace:    at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateSiteCollection.Program.ActivateFeature(String clientUrl, SharePointOnlineCredentials credentials)

Then the script/helper moves on to another client and is successful:

Successfully added users to group: [MyNextClient] Owners
Adding users to group: [MyNextClient] Visitors
Successfully added users to group: [MyNextClient] Visitors
Creating site collection at https://[MyTenant].sharepoint.com/sites/[MyNextClient]
Loading.
....Site Collection: https://[MyTenant].sharepoint.com/sites/[MyNextClient] is created successfully

Although, ultimately, the entire deployment fails because of the exception.

**Comment by DaveyDoo** [comment]
And a similar exception is thrown intermittently when provisioning pages.  The settings.aspx is successfully provisioned for a number of sites, then a (401) Unauthorized error:

Provisioning matter center pages on: https://[MyTenant].sharepoint.com/sites/[MyClientName]
Successfully provisioned the matter center page: settings.aspx
Creating configuration list
Exception while Provisioning Matter Center page: The remote server returned an error: (401) Unauthorized. 
 Stack Trace:    at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.Common.ConfigureSharePointContext.ConfigureClientContext(String Url, String login, String password, Boolean isDeployedOnAzure)
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.CreateProvisionPages(Dictionary`2 configVal, String urlConstantName, String sourceFileTemplate, String pageUrlName, MatterCenterPage pageType)
Exception while Provisioning Matter Center page: The remote server returned an error: (401) Unauthorized. 
 Stack Trace:    at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.Common.ConfigureSharePointContext.ConfigureClientContext(String Url, String login, String password, Boolean isDeployedOnAzure)
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.CreateProvisionPages(Dictionary`2 configVal, String urlConstantName, String sourceFileTemplate, String pageUrlName, MatterCenterPage pageType)

Then it moves to the next client/site and is successful:

Provisioning matter center pages on: https://[MyTenant].sharepoint.com/sites/[MyNextClient]
Successfully provisioned the matter center page: settings.aspx
Creating configuration list
Deleting matter center pages from: https://[MyTenant].sharepoint.com/sites/[MySecondNextClient]
Provisioning matter center pages on: https://[MyTenant].sharepoint.com/sites/[MySecondNextClient]
Successfully provisioned the matter center page: settings.aspx
Creating configuration list

**Comment by sharpzuber** [comment]
I am also getting the above same issue ?
