### ISSUE TITLE
Web Dashbord issue

### ISSUE THREAD

**Issue by johnnyc23** [Microsoft/mattercenter#229]
The Deployment script completed successfully but the Web dashboard was not properly setup. 

here is the log
6/14/2016 3:26:55 PM - Step 15: Provisioning Web dashboard
Deleting matter center pages from: https://sitexyz.sharepoint.com
Exception while Provisioning Matter Center page: List 'Site Pages' does not exist at site with URL 'https://sitexyz.sharepoint.com'.
 Stack Trace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.DeletePages(ClientContext clientContext, List`1 files)
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.CreateProvisionPages(Dictionary`2 configVal, String urlConstantName, String sourceFileTemplate, String pageUrlName, MatterCenterPage pageType)
Deleting matter center pages from: https://sitexyz.sharepoint.com
Exception while Provisioning Matter Center page: List 'Site Pages' does not exist at site with URL 'https://sitexyz.sharepoint.com'.
 Stack Trace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.DeletePages(ClientContext clientContext, List`1 files)
   at Microsoft.Legal.MatterCenter.ProvisionWebDashboard.Program.CreateProvisionPages(Dictionary`2 configVal, String urlConstantName, String sourceFileTemplate, String pageUrlName, MatterCenterPage pageType)
Deleting matter center pages from: https://sitexyz.sharepoint.com/sites/catalog
Provisioning matter center pages on: https://sitexyz.sharepoint.com/sites/catalog
Successfully provisioned the matter center page: documentDetails.aspx
6/14/2016 3:27:03 PM - Completed Provisioning Web dashboard

SO now when I go to access the MC Home the site doesn't exist.  From the Outlook addin, I click the "Go to Matter Center Home" and page/site doesn't exist. 

How can I resolve this?

**Comment by AkashVirani** [comment]
Hello @johnnyc23 ,
 
Kindly refer to the deployment document [Matter Center Build and Deployment Guide.docx ](https://github.com/Microsoft/mattercenter/blob/master/tree/master/cloud/docs/Matter%20Center%20Build%20and%20Deployment%20Guide.docx) and perform the step no. 3 (Provision Web dashboard page) under Appendix A. 
This step is used to provision the Web dashboard manually.

**Comment by johnnyc23** [comment]
I had to leave the project but relayed the information to other members. I will try to find out.

**Comment by amitabhm21** [comment]
Thanks. I am going to close this issue. Please re-open as needed.

**Comment by asadrajput** [comment]
Hi I am getting WEB_DASHBOARD_PAGE_URL not found when I browse the /Pages/MatterCenterHome.aspx.
Could you please help? 
I have followed the steps in step 3 but I don't understand this step:
•	URL should be Azure web dashboard as below 
![capture](https://cloud.githubusercontent.com/assets/24537830/21127718/3e532e8e-c149-11e6-9480-4d66fdf78e5a.PNG)
