### ISSUE TITLE
Installation fails during step 4

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#23]
I've ran the installation after I made all the changes as described in the documentation.

The PowerShell returns the following errors and then reverts all the changes: Any idea what could be wrong?

....
Updating app schema files
C:\Git\mattercenter\tree\master\cloud\src\deployments
Updating Microsoft.Legal.MatterCenter_Outlook.xml file
Message: StartIndex cannot be less than zero.
Parameter name: startIndex
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateManifest(String inputXMLFile, Dictionary`2 excelInput, String sSourceLocation, String sDefaultValue, String startPageElement, Boolean iFlag)
Successfully updated Microsoft.Legal.MatterCenter_Outlook.xml file
Updating Microsoft.Legal.MatterCenter_Office.xml file
Message: StartIndex cannot be less than zero.
Parameter name: startIndex
Stacktrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateManifest(String inputXMLFile, Dictionary`2 excelInput, String sSourceLocation, String sDefaultValue, String startPageElement, Boolean iFlag)
Successfully updated Microsoft.Legal.MatterCenter_Office.xml file
Successfully updated app schema files
18/12/2015 11:56:34 - Updating Office, Outlook and SharePoint App schema files failed
18/12/2015 11:56:34 -
18/12/2015 11:56:34 - Reverting till step 3
....

I'm assuming that there is something wrong with the xml mentioned. Here a copy of the contents. In the original config file there was  <AppDomain>https://service.azurewebsites.net</AppDomain>
what is this referring to? I couldn't find what needs to be created here. So could this be the problem?

<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="MailApp">
  <Id>EBE8EFF1-3206-4A7F-8ADA-102139367014</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Microsoft Corporation</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Matter Center Beta" />
  <Description DefaultValue="Matter Center Beta App allows you to search Matters, Documents and create Matter for particular Client" />
  <IconUrl DefaultValue="https://www.siteicons.com/mcicon.gif" />
  <AppDomains>
    <AppDomain>https://login.microsoftonline.com/</AppDomain>
    <AppDomain>https://matters.azurewebsites.net</AppDomain>
    <AppDomain>https://matters.azurewebsites.net</AppDomain>
    <AppDomain>https://matters.sharepoint.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://matters.azurewebsites.net/pages/Home.aspx?appType=Outlook" />
        <RequestedHeight>450</RequestedHeight>
      </DesktopSettings>
      <TabletSettings>
        <SourceLocation DefaultValue="https://matters.azurewebsites.net/pages/Home.aspx?appType=Outlook" />
        <RequestedHeight>300</RequestedHeight>
      </TabletSettings>
      <PhoneSettings>
        <SourceLocation DefaultValue="https://matters.azurewebsites.net/pages/Home.aspx?appType=Outlook]" />
      </PhoneSettings>
    </Form>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://matters.azurewebsites.net/pages/Home.aspx?appType=Outlook]" />
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Read" />
  </Rule>
</OfficeApp>

**Comment by PieterVeenstra** [comment]
I've done some more investigation and I found out that the logo has to live within a path with a folder or library with the name 'Images'.
