### ISSUE TITLE
Error in step 5.

### ISSUE THREAD

**Issue by 2source4** [Microsoft/mattercenter#262]
When i run the Deploy script i get an error in step 5:
11-7-2016 10:17:35 - Step 5: Update Search Configuration files and upload to SharePoint
Message: This configuration change cannot be made at this time because the service is in read-only mode.
Stacktrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.UpdateSearchConfig(String filePath, String login, String password)
11-7-2016 10:17:39 - Updating Search Configuration failed.

Does anyone know how to solve this issue?

Edit:
one day later it started working.

**Comment by amitabhm21** [comment]
@2source4 is this issue still open?

**Comment by 2source4** [comment]
no it started working somehow. 
I guess there was a problem in SharePoint online.
