### ISSUE TITLE
"There is already a term with the same default label and parent term"

### ISSUE THREAD

**Issue by kspizzle** [Microsoft/mattercenter#411]
Creating practice group Litigation
        Creating area of law Intellectual Property
                Creating sub area of law Copyright
                Creating sub area of law Patent
Message: There is already a term with the same default label and parent term.
Stacktrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateTerm.CreateTerm.CreateTermsForClients(List`1 TermsData, ClientContext clientContext)
   at Microsoft.Legal.MatterCenter.CreateTerm.CreateTerm.CreateClientTerms(Dictionary`2 listval, List`1 TermsData)
13/09/2016 17:02:28 - Creating taxonomy hierarchy failed

I think this may be due to previous attempts at setting up Matter Center, I have created a new app catalog and stripped back the Excel to just Liltigation > Copyright and Litigation > Patent, but still this error persists - any  help most welcome!

**Comment by amitabhm21** [comment]
Would you try deleting the practice group Litigation and run the script again? It is difficult to help in scenario as we don't have visibility to your term store. 
If its a dev environment maybe you can share ?

**Comment by premchandpl** [comment]
@kspizzle Is this still an issue?

**Comment by premchandpl** [comment]
@kspizzle Closing this. Get latest matter center v2 version and try with the new version which is much more simplified
