### ISSUE TITLE
Issue with Deploy.ps1, Step 2

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#683]
Deploy.ps1 fails at Step 2. When prompted I log in as the Primary Administrator for the site. 

Step 2: Create taxonomy hierarchy
Reading inputs from Excel...
Deleting existing taxonomy hierarchy
Message: Access denied. You do not have permission to perform this action or access this resource.
Stacktrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.CreateTerm.CreateTerm.DeleteMatterCenterTerms(List`1 TermsData, ClientContext clientContext)
   at Microsoft.Legal.MatterCenter.CreateTerm.CreateTerm.DeleteTerms(Dictionary`2 listval, List`1 TermsData)

**Comment by allenolayiwola** [comment]
Is the excel sheet open while trying to run this script. Ran into a similar issue cause the excel file was still open during the script! Please check.

**Comment by mcpsmith** [comment]
Yes the excel sheet is closed. It looks like it was able to successfully read the spreadsheet in step 1b.  It runs into issues in Step 2: Create taxonomy heirararchy.

**Comment by mcpsmith** [comment]
Fixed it - my user was not a Term Store Administrator
