### ISSUE TITLE
Issue with Deploy.ps1: Step 4

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#687]
Running into the following error when running Deploy.ps1:

3/6/2017 10:03:24 AM - Step 4: Update Search Configuration files and upload to SharePoint
Deleting a SerchConfig if it exists
Message: Cannot complete this action.

Please try again.
Stacktrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.Legal.MatterCenter.UpdateAppConfig.UpdateConfig.RevertSearchConfig(ClientContext clientContext, SearchConfigurationPortability searchConfigs, XDocument resultSourceXml, SearchObjectOwner owner, String errorFilePath)

**Comment by mcpsmith** [comment]
Taking my cue from another issue, I just kept rerunning the script. It worked after 4 more tries, spaced out over 2 hours.
