### ISSUE TITLE
Error in last step in deployment, SPOAuthorization.GetClientContext

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#694]
Getting errors on the last steps when trying to click on "Update labels for matter center" and "Update labels for details page in sharepoint site". 

DescriptionError occured in the system. Please contact the administrator
MessageOne or more errors occurred.
ErrorCode500
MethodNameGetClientContext
ClassNameSPOAuthorization
LineNumber 80
StackTrace at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.GetClientContext(String url) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Utility\Authorization\SPOAuthorization.cs:line 80
 at Microsoft.Legal.MatterCenter.Repository.SPList.CheckPermissionOnList(Client client, String listName, PermissionKind permission) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPList.cs:line 519
 at Microsoft.Legal.MatterCenter.Service.MatterController.CanCreateMatter(Client client) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\Controllers\MatterController.cs:line 526

**Comment by AISDUG** [comment]
@mcpsmith Please check to see if your Azure Subscription is set to at least Basic(B1). This is required in order for the SSL certificate to work correctly.

**Comment by mcpsmith** [comment]
Yes It is set to B1.  I am able to get the "Update labels for details page in sharepoint site" link to work successfully but the "Update labels for matter center" link now displays the following error: 
"MessageNetwork issue. Unable to get the response from the server."

**Comment by mcpsmith** [comment]
Followed Steps 8 and 9 to set up matter center permissions - thought this didn't have to be done because they are in the same tenant, but following the steps got me past this issue.

**Comment by mcpsmith** [comment]
@AISDUG  - the subscription was set to B1.  Started working after following steps 8 and 9. Thank you.

**Comment by shijov** [comment]
Getting an error at step 10, when I open the /#/admin URL of the web app

DescriptionError occured in the system. Please contact the administrator
MessageOne or more errors occurred.
ErrorCode500
MethodNameGetClientContext
ClassNameSPOAuthorization
LineNumber 80
StackTrace at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.GetClientContext(String url) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Utility\Authorization\SPOAuthorization.cs:line 80
 at Microsoft.Legal.MatterCenter.Repository.SPList.CheckPermissionOnList(Client client, String listName, PermissionKind permission) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Service\Microsoft.Legal.MatterCenter.Repository\SharePointInfo\SPList.cs:line 500
 at Microsoft.Legal.MatterCenter.Service.MatterController.CanCreateMatter(Client client) in C:\mattercenter-master\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\Controllers\MatterController.cs:line 526

Followed Step 8 and 9 but it did not resolve my issue.

@AISDUG We are using a Microsoft Bulk Credit subscription. The offer name is Unknown as shown in azure as below. Will this still make the SSL to work incorrectly?

![image](https://cloud.githubusercontent.com/assets/28421764/25731543/bb6635c4-3179-11e7-8e96-f232963d1f58.png)
