### ISSUE TITLE
Matter search doesn't work

### ISSUE THREAD

**Issue by sbammer** [Microsoft/mattercenter#766]
Clicking on Matters in main Mattercenter screen doesn't return anything - just a spinner.  F12 console shows this:

Error: [$resource:badcfg] http://errors.angularjs.org/1.5.8/$resource/badcfg?p0=Error%20in%20resource%20configuration%20for%20action%20%60%7B0%7D%60.%20Expected%20response%20to%20contain%20an%20%7B1%7D%20but%20got%20an%20%7B2%7D%20(Request%3A%20%7B3%7D%20%7B4%7D)&p1=get&p2=array&p3=object&p4=POST&p5=%2Fapi%2Fv1%2Fmatter%2Fget
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/angular-resource/1.5.8/angular-resource.js:777:19)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:131:10)
   at m.prototype.$eval (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:145:336)
   at m.prototype.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:142:412)
   at m.prototype.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:146:111)
   at l (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:97:320)
   at J (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angu

I checked the Mattercenter source ID in the result sources section per another issue resolution and the ID already matches in the app settings section in Azure.

**Comment by premchandpl** [comment]
@sbammer Can you please look int the issue where the solution has been provided
https://github.com/Microsoft/mattercenter/issues/759

**Comment by sbammer** [comment]
Where do I go to fix this with the information in the post you referenced?  I’m not a developer.

Thanks

Steve           Bammer

SharePoint Administrator

Kemper Corporate Services
One Tower Lane, Lower Level     ,       Oakbrook Terrace        ,       IL              60181


630.368.8063<tel:630.368.8063>   /      +1 6307884782<tel:+1%206307884782>       Cell

sbammer@kemper.com<mailto:sbammer@kemper.com>
www.kemper.com<http://www.kemper.com/>

[cid:image184680.jpg@C32DD044.812F9F79]

**Comment by sbammer** [comment]
I followed your fix by adding the new Managed Property - it works!  Thanks!!!!
