### ISSUE TITLE
Step 10: Error 500 - An error occurred while starting the application.

### ISSUE THREAD

**Issue by rakoellner** [Microsoft/mattercenter#769]
Hi team,
I have no issues while the installation process via Office 365and publish the WebApp successfully via Visual Studio 2015: 

Web App was published successfully http://mattercenter08101025.azurewebsites.net/
========== Build: 4 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

But the WebApp shows me: 500 Internal Server Error - An error occurred while starting the application.

Any ideas? 

Thank you very much
Raphael

**Comment by rakoellner** [comment]
Log-Stream

"2017-08-12T21:33:53
System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified. Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---

2017-08-12T21:33:53  PID[5852] Information 
2017-08-12T21:33:53  PID[5852] Information D:\local\Temp\jobs\continuous\MatterCenterWebJobs\cnyrnyqc.4pc\win7-x64>Microsoft.Legal.MatterCenter.Jobs.exe
2017-08-12T21:33:54  PID[5852] Error       
2017-08-12T21:33:54  PID[5852] Error       Unhandled Exception: System.ArgumentNullException: Value cannot be null.
2017-08-12T21:33:54  PID[5852] Error       Parameter name: clientId
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate..ctor(String clientId, X509Certificate2 certificate)
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.KeyVaultHelper.GetCert(IConfiguration configurtaion) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\KeyVaultHelper.cs:line 149
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.Program.Main(String[] args) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\Program.cs:line 22"

**Comment by rakoellner** [comment]
Log-Stream Part 2

2017-08-12T21:33:53
System.ApplicationException: The trace listener AzureBlobTraceListener is disabled. ---> System.InvalidOperationException: The SAS URL for the cloud storage account is not specified. Use the environment variable 'DIAGNOSTICS_AZUREBLOBCONTAINERSASURL' to define it.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.RefreshConfig()
   --- End of inner exception stack trace ---

2017-08-12T21:33:53  PID[5852] Information 
2017-08-12T21:33:53  PID[5852] Information D:\local\Temp\jobs\continuous\MatterCenterWebJobs\cnyrnyqc.4pc\win7-x64>Microsoft.Legal.MatterCenter.Jobs.exe
2017-08-12T21:33:54  PID[5852] Error       
2017-08-12T21:33:54  PID[5852] Error       Unhandled Exception: System.ArgumentNullException: Value cannot be null.
2017-08-12T21:33:54  PID[5852] Error       Parameter name: clientId
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate..ctor(String clientId, X509Certificate2 certificate)
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.KeyVaultHelper.GetCert(IConfiguration configurtaion) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\KeyVaultHelper.cs:line 149
2017-08-12T21:33:54  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.Program.Main(String[] args) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\Program.cs:line 22
2017-08-12T21:34:54  PID[5852] Information 
2017-08-12T21:34:54  PID[5852] Information D:\local\Temp\jobs\continuous\MatterCenterWebJobs\cnyrnyqc.4pc\win7-x64>Microsoft.Legal.MatterCenter.Jobs.exe
2017-08-12T21:34:55  PID[5852] Error       
2017-08-12T21:34:55  PID[5852] Error       Unhandled Exception: System.ArgumentNullException: Value cannot be null.
2017-08-12T21:34:55  PID[5852] Error       Parameter name: clientId
2017-08-12T21:34:55  PID[5852] Error          at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate..ctor(String clientId, X509Certificate2 certificate)
2017-08-12T21:34:55  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.KeyVaultHelper.GetCert(IConfiguration configurtaion) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\KeyVaultHelper.cs:line 149
2017-08-12T21:34:55  PID[5852] Error          at Microsoft.Legal.MatterCenter.Jobs.Program.Main(String[] args) in C:\projects\mc2\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Jobs\Program.cs:line 22

**Comment by rakoellner** [comment]
noone?

**Comment by premchandpl** [comment]
@rakoellner Can we have skype meeting and I can look into this. My skype id is - premchand_76@hotmail.com

**Comment by heckshmek** [comment]
I am also seeing this same issue. Were you able to find a solution?
