### ISSUE TITLE
Error 500 after web application deployment

### ISSUE THREAD

**Issue by tgarmon** [Microsoft/mattercenter#830]
I have to say, I was very excited to deploy this solution, but after spending over 30 hours with multiple deployments on fresh accounts, I am rather at my wits end. I've gone from excited to desperate to get this running before i put any more IT money down a black hole. I am willing to pay to solve this issue, please email me at tgarmon@wcwpllc.com, or I will happily take suggestions. From running test this appears to be the "cancreate" process

DescriptionError occured in the system. Please contact the administrator
MessageOne or more errors occurred.
ErrorCode500
StackTrace at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at System.Threading.Tasks.Task`1.get_Result()
 at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.GetClientContext(String url)
 at Microsoft.Legal.MatterCenter.Repository.SPList.CheckPermissionOnList(Client client, String listName, PermissionKind permission)
 at Microsoft.Legal.MatterCenter.Repository.MatterRepository.CanCreateMatter(Client client)
 at Microsoft.Legal.MatterCenter.Service.MatterController.CanCreateMatter(Client client)

In the Sharepoint apps for office section I looked at the XML of the Microsoft.Legal.MatterCenter_Office.xml file, and this is what I see. 

<?xml version="1.0" encoding="UTF-8"?>

-<OfficeApp xsi:type="TaskPaneApp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/office/appforoffice/1.1">
<Id>2076412a-e554-414c-9221-fdcd515794dc</Id>
<Version>1.0.0.0</Version>
<ProviderName>Microsoft Corporation</ProviderName>
<DefaultLocale>en-US</DefaultLocale>
<DisplayName DefaultValue="Matter Center"/>
<Description DefaultValue="Matter Center App allows you to search matters, document, filing documents to matter and even create new matters."/>
<IconUrl DefaultValue="https://MattersWeb02180441.azurewebsites.net/Images/32x32-logo.png"/>
<HighResolutionIconUrl DefaultValue="https://matterwebapp.azurewebsites.net/Images/64x64-logo.png"/>
-<AppDomains>
<AppDomain>https://MatterCenterWeb12112301.azurewebsites.net</AppDomain>
<AppDomain>https://M365x102144.sharepoint.com</AppDomain>
<AppDomain>https://login.microsoftonline.com/</AppDomain>
</AppDomains>
-<Hosts>
<Host Name="Document"/>
</Hosts>
-<DefaultSettings>
<SourceLocation DefaultValue="https://MattersWeb02180441.azurewebsites.net"/>
</DefaultSettings>
<Permissions>Restricted</Permissions>
</OfficeApp>

![update labels](https://user-images.githubusercontent.com/26411605/36551514-590d8b22-17bd-11e8-9d5b-0b80ba28def3.png)

![labels2](https://user-images.githubusercontent.com/26411605/36551653-b7c1fab8-17bd-11e8-8253-461bf8e983ac.png)

I have Matter Center on same tenant .onmicrosoft.com. We have published the web application.  I attempted to complete step 10, but I could not update labels for details page in SharePoint site. Everytime a page loads there is an "ERROR." some screens it has a popup with SPO issues. I have attached the screenshot
![issues](https://user-images.githubusercontent.com/26411605/36550192-56b1dc28-17ba-11e8-9b20-e4ec86f10355.jpg)
![issues2](https://user-images.githubusercontent.com/26411605/36550227-6ba5b1a4-17ba-11e8-84f5-89026948accf.jpg)
![issues3](https://user-images.githubusercontent.com/26411605/36550235-706beece-17ba-11e8-9fe9-0d88901be0cc.jpg)

**Comment by SofianeBen** [comment]
Have you identified a solution for this issue>

**Comment by tgarmon** [comment]
No, we have not. We have tried on multiple machines. That's why I am reopening this issue.

**Comment by umeboshi2** [comment]
This issue may be related: Microsoft/Dynamics-AX-Integration#5

**Comment by tgarmon** [comment]
@umeboshi2 , I changes the "oauth2AllowImplicitFlow": true, It was set to false in the manifest.

**Comment by tgarmon** [comment]
This did not resolve the issue.

**Comment by adrenaline1073** [comment]
@tgarmon I found that all my issues were solved when I was setting up the permissions, I was adding them but not applying them in azure.  Mind you it took me like a month to fix it though.  Hope that helps.
